### ISSUE TITLE
Custom intent not handled

### ISSUE THREAD

**Issue by cfvescovo** [stanwood/alexa-skill#2]
Your module cannot handle custom intents. In fact your `mapper()` function is empty. 
Could you solve it?

**Comment by cfvescovo** [comment]
If you need help, ask me. I would be happy to help you with this excellent project

**Comment by rglsk** [comment]
@BaldEagleX02 Hey, thanks for the notice 👍 

1. What do you mean by `mapper()` function is empty? 
2. Are you talking about property defined in abstract class `BaseIntents`? 
The approach for this is that every intent should implement this property.

Please feel free to create a PR with a fix, I can do it but unfortunately not soon :)

**Comment by cfvescovo** [comment]
I have found out that base.py (Intents folder) has an empty function named `mapper` (which the module uses to create a dict with intents names and methods)

**Comment by cfvescovo** [comment]
How should this dict be structured? Something like`{'intent_name' : 'intent_method'}` ?

**Comment by cfvescovo** [comment]
How can I call methods from your module? I can only see (<quote.NameClass object at memory_address>) when I print the intents object from your module. I know I can't call functions from their memory address.

**Comment by rglsk** [comment]
@BaldEagleX02 yes sir, exactly, we should add it to the property doc string as well. 
 
As we can see README.md and [examples](https://github.com/stanwood/alexa-skill/blob/master/examples/falcon_app/main.py#L34-L38) might not be enough ;)

**Comment by cfvescovo** [comment]
Yes, I did it, but it doesn't work

**Comment by BaldEagleX02** [comment]
```
def mapper(self):
         """
         Dictionary which map alexa intent name with intent method name.
 
         :rtype dict
         """
```
This function is empty. It has only some comments.

**Comment by rglsk** [comment]
@BaldEagleX02 Are you trying to call the abstract class directly? 
Please read about [abstract classes](https://docs.python.org/2.7/library/abc.html) and what is the purpose of them :)

**Comment by cfvescovo** [comment]
No, I'm not

**Comment by cfvescovo** [comment]
I cannot call the ABC directly

**Comment by cfvescovo** [comment]
I implemented my mapper function in my code as a property with the property decorator but when I make a request it doesn't get handled correctly

**Comment by cfvescovo** [comment]
I finally solved editing your init.py file!!
I inserted this code and it worked: `self.intents_mapper = intents[0].mapper`
(I have only one intent)

If you have multiple intents you should iterate over them

**Comment by adecchi-2inno** [comment]
HI @Piotr-Rogulski 
I follow your readme and created a custom intents, but I get an error:
`ERROR:root:Intent name: MyIntentName not handled`
I have to edit the file alexa_skill/__init__.py and replace self.intents_mapper = {} by self.intents_mapper = intents[0].mapper

**Comment by adecchi-2inno** [comment]
@Piotr-Rogulski 
I added the following lines below :
 ` self.intents_mapper = {}       
for intent in range(len(intents)):
      self.intents_mapper.update(intents[intent].mapper)`
